In [1]:
# Initial imports
# INSTALL PIP
# pip install yfinance

import os
import requests
import pandas as pd
from dotenv import load_dotenv
import yfinance as yf
import datetime
from datetime import date
import hvplot.pandas

%matplotlib inline

ModuleNotFoundError: No module named 'dotenv'

## Part 1 - Collect Stock Data

In [2]:
# The Stocks we'll use for this project
stock_list = ['FB', 'AAPL', 'GOOGL', 'AMZN', 'NFLX']

In [3]:
# set timeframe
startdate = datetime.datetime(2020,1,1)
enddate = date.today().strftime('%Y-%m-%d')

In [4]:
# Grab Data
Facebook = yf.Ticker("FB")
Apple = yf.Ticker("AAPL")
Netflix = yf.Ticker("NFLX")
Amazon = yf.Ticker("AMZN")
Google = yf.Ticker("GOOGL")

In [5]:
# define stock_list

stock_df = yf.download(
    "AMZN FB GOOGL NFLX AAPL",
    start = startdate,
    end = enddate,
    group_by = "ticker"
)

stock_df.tail()

[*********************100%***********************]  5 of 5 completed

                    FB                                                  \
                  Open        High         Low       Close   Adj Close
Date
2022-04-28  202.919998  208.529999  192.899994  205.729996  205.729996
2022-04-29  204.460007  212.479996  199.899994  200.470001  200.470001
2022-05-02  201.169998  211.880005  200.990005  211.130005  211.130005
2022-05-03  210.449997  214.899994  208.089996  212.029999  212.029999
2022-05-04  210.649994  224.300003  206.960007  223.410004  223.410004

                              AMZN                                         \
               Volume         Open         High          Low        Close
Date
2022-04-28  100890600  2843.560059  2918.750000  2806.000000  2891.929932
2022-04-29   49137200  2596.979980  2615.219971  2432.500000  2485.629883
2022-05-02   49915300  2448.020020  2493.360107  2367.500000  2490.000000
2022-05-03   41556300  2481.070068  2524.409912  2456.500000  2485.070068
2022-05-04   41375900  2472.000000  2520.000000  2383.659912  2518.570068

            ...        GOOGL                                           NFLX  \
            ...          Low        Close    Adj Close   Volume        Open
Date        ...
2022-04-28  ...  2282.300049  2370.449951  2370.449951  2444200  191.559998
2022-04-29  ...  2276.290039  2282.189941  2282.189941  2131800  198.679993
2022-05-02  ...  2252.000000  2331.659912  2331.659912  1776700  191.710007
2022-05-03  ...  2320.689941  2346.679932  2346.679932  1248400  198.289993
2022-05-04  ...  2302.320068  2445.219971  2445.219971  2495800  197.649994


                  High         Low       Close   Adj Close    Volume
Date
2022-04-28  201.479996  185.600006  199.520004  199.520004  21363200
2022-04-29  204.710007  190.000000  190.360001  190.360001  16356600
2022-05-02  200.210007  190.009995  199.460007  199.460007  14591600
2022-05-03  203.199997  194.770004  199.869995  199.869995  11839400
2022-05-04  204.380005  191.009995  204.009995  204.009995  12218800

[5 rows x 30 columns]

In [6]:
# define each stock
fb_df = stock_df["FB"]
aapl_df = stock_df["AAPL"]
amzn_df = stock_df["AMZN"]
nflx_df = stock_df["NFLX"]
googl_df = stock_df["GOOGL"]

In [9]:
# Historical view of the closing price for each stock
closing_df = stock_df.groupby("Date")["Close"]

closing_df.tail()

KeyError: 'Column not found: Close'